### PR TITLE
Resend all gerrit patches

### PR DESCRIPTION
**Pull request by martinetd**
This has lots of unrelated commits, it's probably better to split this but I'm opening this for now before I forget.

I've marked the gerrit project as hidden, so now the project no longer shows up and all the patches are gone:
https://review.gerrithub.io/q/project:cea-hpc/phobos is empty
admins can still access the project settings page:
https://review.gerrithub.io/admin/repos/cea-hpc/phobos,general
from there you can change the "State", top of repository options, if required (it's also possible to make it read only, but not sure how clear that'd be until someone actually tries to push, I think it's better to hide it)

### CODE REVIEW

**Review by patlucas — APPROVED** [review]
I have no other comment on this patch than it seems usefull ! I cherry-pick it on our local CI cluster and we will close this commit here on github when it will be integrated.

**Review by patlucas — COMMENTED** [review]
The patch 

"comm: pho_comm_open: allow binding interface for tcp server " fails the non-regression tests.

I will investigate and come back soon with an explanation.

**Comment by patlucas** [comment]
> I have no other comment on this patch than it seems usefull ! I cherry-pick it on our local CI cluster and we will close this commit here on github when it will be integrated.

This first message was about the first commit : "[comm: guard freeaddrinfo() calls](https://github.com/phobos-storage/phobos/pull/12/commits/b9bdacddf84ab36b66cd59afc3c244f985c46669)"

**Comment by patlucas** [comment]
> > I have no other comment on this patch than it seems usefull ! I cherry-pick it on our local CI cluster and we will close this commit here on github when it will be integrated.
> 
> This first message was about the first commit : "[comm: guard freeaddrinfo() calls](https://github.com/phobos-storage/phobos/pull/12/commits/b9bdacddf84ab36b66cd59afc3c244f985c46669)"

This first commit is integrated to our local master branch and will be soon pushed to github.

**Comment by martinetd** [comment]
This was no longer mergable because of a few conflicts (TLC, python CLI)

Having a large PR is hard to track and merge patches individually, but if you prefer a large branch then I've updated my 'gerrit_patches' branch with all the patches, feel free to use it to push to your gerrit.

(Long term a better way to contribute (access to the internal gerrit? move actual development/reviews to something public?) would be appreciated... We can re-discuss this once paperwork moves a bit)

**Pull request closed without merging**
